server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: java-study.cszujt9uaieq.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin1q2w3e4r
    password: 1q2w3e4r

mybatis:
  mapper-location:
    - /mappers/*.xml
